### ISSUE TITLE
Skript not understanding creating a new document

### ISSUE THREAD

**Issue by lj-pixel** [Romitou/MongoSK#16]
My code is `        save {_new} in collection named "users" from database named "playerstats" with client named "central"` and it returns 'cannot understand this condition/effect'

**Comment by Romitou** [comment]
Hi,

In fact, the pattern for the collection expression is `[mongo[db]] database [(named|with name|called)] %string% (of|with) %mongoclient%`. Try replacing `from` with `of` or `with`.

However, I will add `from` to the syntax in the next version as it makes sense for it to be part of the pattern.

Thank you for opening this issue!
