### ISSUE TITLE
Sort Collection Expression/Effect

### ISSUE THREAD

**Issue by ReportCardsMC** [Romitou/MongoSK#17]
An expression in which you can sort a collection and get the result, this would be very useful for getting top players depending on a certain index and value.

Example Syntax: `[mongo] sort collection %collection% by %string% from (highest to lowest|lowest to highest)`
Example Usage: 
````
set {_sort::*} to sort collection {_collection} by "balance" from highest to lowest
loop 3 times:
    send "%loop-value%. %{_sort::%loop-value%}%" to {_player}

**Comment by Romitou** [comment]
Sure! I'll look as soon as I can free up some time.

**Comment by Romitou** [comment]
This enhancement has been added in the https://github.com/Romitou/MongoSK/commit/053607e94676d70efbc7e2204c7195fa51189bc1 commit.

Example:
```py
# Inline query:
set {_documents::*} to all descending sorted mongo documents in {collection} by fields "coins" and "joinedTimestamp"

# More unpacked query:
set {_query} to mongo documents in {collection}
set {_sortedQuery} to descending sorted {_query} by fields "number"
set {_documents::*} to all documents of {_sortedQuery}
```

This commit brings major changes to the code and especially to the way the addon handles queries.
In my opinion, I think that the syntaxes are starting to become difficult to read, so I prefer to warn that the syntaxes added by this commit are very likely to be modified in the future. Please do not hesitate to let me know if there are any problems!

**Comment by ReportCardsMC** [comment]
With this, is it possible to sort all documents where a filter is in place as well?

**Comment by Romitou** [comment]
Of course! Unfortunately it seems to me that this new version has some problems. I recommend you to wait for the arrival of the major version 2.0 of MongoSK which will be built more solidly and bring more functionalities, being currently greatly limited by the support of backward compatibility.
