### ISSUE TITLE
Modify the entire document at once

### ISSUE THREAD

**Issue by LoganLilypad** [Romitou/MongoSK#19]
Currently we are only able to set individual values in MongoSK `set list "example" of {_document} to 10, 54 and 203`

But it would be nice to set the entire document's content at once like `set {_document}'s mongo json to "{""yes"":""no""}"`
And/or the addition to convert the document to Skript lists and vise versa

I know Skript-json already has the Skript list <-> json functionality but I think both of these addons could work nicely together if this was added.

**Comment by Romitou** [comment]
Hello, it will be completely possible to create a document from a JSON text in the v2 version of MongoSK.
You will normally be able to work with skript-json without any problem, i.e. :
- retrieve the JSON of a document (MongoSK) ;
- convert it into a variable (skript-json) ;
- make your modifications of the mapped variable (Skript) ;
- convert your variable into JSON (skript-json) ;
- define the JSON of a document (MongoSK).

Does this seem correct to you, or would you like a direct implementation in MongoSK?

**Comment by LoganLilypad** [comment]
Yep that seems good, I was just curious if there was a plan/way to create a document straight from JSON

**Comment by Romitou** [comment]
This has been implemented in MongoSK v2. 😄
