### ISSUE TITLE
Use of '?' operator.

### ISSUE THREAD

**Issue by AdxmGG** [Romitou/MongoSK#27]
Although not urgent, I just think this would be useful addition to MongoSK.

```
set {%{_U}%::points} to mongo value "points" of {_document}
    if {%{_U}%::points} is not set:
        set {%{_U}%::points} to 0
```
can be shortened to

```set {%{_U}%::points} to mongo value "points" of {_document} ? 0```

**Comment by Olyno** [comment]
Not recommanded because it required last Skript version for this syntax.

**Comment by Skylyxx** [comment]
It seems to me that this is already possible, right? Is an addition in mongosk necessary?

**Comment by AdxmGG** [comment]
> It seems to me that this is already possible, right? Is an addition in mongosk necessary?

I tried it myself, no luck, and asked the developer who said it would not work. So I don't  think this is already possible in this case.

**Comment by Romitou** [comment]
Here, it is a default expression already integrated by Skript, so the pattern would have to be modified.
As discussed on the Discord server, the utility would be of the get or create the value, for example:
```applescript
set {_doc} to a new mongo document
set {_test} to mongo value "foo" of {_doc} # {_test} = <none>
set {_test} to mongo value "foo" of {_doc} with default value "bar" # {_test} = "bar"
```
So in reality, the behaviour of Skript is not similar to this suggestion, and I think it's a good idea to implement it for me (but with another pattern).

**Comment by Romitou** [comment]
After double checking, it is possible to do this directly with Skript. Just add parentheses, like this:
```applescript
set {%{_U}%::points} to (mongo value "points" of {_document}) ? 0
```
Sorry for the delay in responding, I thought you were asking for a different feature than Skript. Have fun!
