### ISSUE TITLE
Can't create a value in Array

### ISSUE THREAD

**Issue by Drapika** [Romitou/MongoSK#39]
Hello !

I start learn MongoSK and I look the documentation from SkUnity but, I don't see how Can I create a value in a Array in doc of my collection 🤔 It's possible or not ? And if yes, what's the syntaxe for ? Help please 🤣

I use the last Pre-Release of MongoSK

Thinks for reply ! 😁😁

**Comment by Romitou** [comment]
Hey @Drapika,

Let's say you have a Mongo document that looks like this: `{"foo": "bar", "roles": ["ADMIN", "MODERATOR"] }`, and you want to add the value "PLAYER" to the `roles` array. For this, it is very simple, `{_doc}` being a variable containing the above document:
```applescript
# 1. Retrieve the array
set {_roles::*} to mongo value "roles" of {_doc}
# -> {_roles::*} is a classic Skript array containing "ADMIN" and "MODERATOR"

# 2. Update the array
add "PLAYER" to {_roles::*}
# -> {_roles::*} is now "ADMIN", "MODERATOR" and "PLAYER"

# 3. Update document's array
set mongo value "roles" of {_doc} to {_roles::*}
# -> We replace the old array with our new array, which we have modified

# 4. Continue to modify your values, save the document, etc.
```

Please let me know if this answers your questions!
Cheers ✌️

**Comment by Drapika** [comment]
Hey ! 

Thinks for our reply ! It's work 😁 But excuse me but I have another question 😅 How i add a value in "PLAYER" object ? Exemple : rank: true in "PLAYER"

**Comment by Romitou** [comment]
To do this, all you need to do is use the same process and logic as before, except that you are not going to add a text, but rather a document that you have created beforehand. In concrete terms, assuming that `{_doc}` is a Mongo document with the content `{"foo": "bar", "roles": [{"id": 1, "name": "Admin"}, {"id": 2, "name": "Moderator"}]` :

```applescript
# 1. Retrieve the array
set {_roles::*} to mongo list "roles" of {_doc}
# -> {_roles::*} is a classic Skript array containing your 2 roles documents

# 2. Create your new role document (= object)
set {_newRole} to a new mongo document with:
    mongo value "id": 1
    mongo value "name": "Player"

# 3. Update the array
add {_newRole} to {_roles::*}
# -> {_roles::*} now contains 3 role documents, including your new role

# 4. Update document's array
set mongo list "roles" of {_doc} to {_roles::*}
# -> We replace the old array with our new array, which we have modified

# 4. Continue to modify your values, save the document, etc.
```

I hope my explanations are clear, don't hesitate to tell me if they are not. 😁

**Comment by Drapika** [comment]
Thinks it's work ! 😁

**Comment by Romitou** [comment]
I am closing this issue, do not hesitate to come back to me if needed 😉
