### ISSUE TITLE
Add support of Skript types

### ISSUE THREAD

**Issue by Romitou** [Romitou/MongoSK#4]
Currently, only Mongo types can be used in documents. It would be essential to be able to set up the support of the Skript types, and otherwise, send an error and not save the value.

**Comment by ReportCardsMC** [comment]
Is this still planned/in the works? I'd love to see this as it'd be a great feature.

Out of curiosity, this means it could save items with nbt as well?

**Comment by Romitou** [comment]
For the time being, an experimental version has already been included in 1.1.1. However, the implementation has not yet been fully completed and some codecs have not yet been implemented. I plan to add the missing ones and to implement a feature to deserialize into the desired object as soon as possible.

I don't guarantee anything for NBT at the moment, but I will do my best to add this!

**Comment by ReportCardsMC** [comment]
Any updates on this and/or an estimate as to when it could be completed?

**Comment by Romitou** [comment]
I'm planning it for the v2 version. I would like to publish this new version before the end of February, depending on my free time or contributions.

**Comment by Romitou** [comment]
This has been implemented in MongoSK v2. 😄
