### ISSUE TITLE
Is there a way to get all documents in a collection?

### ISSUE THREAD

**Issue by ReportCardsMC** [Romitou/MongoSK#6]
I'm genuinely confused, is there or will there be a way to get all the documents in a collection?

**Comment by Romitou** [comment]
Hey!

Sorry to hear that the documentation is confusing. 😢
Feel free to tell me what you change! 😄

For the moment, it is only possible to return a single document from a collection. The addition of this feature will come very soon for 1.2.0.

Don't hesitate if you have other suggestions or requests! 😎

**Comment by Romitou** [comment]
Closing in favour of #7
