### ISSUE TITLE
More Document Features

### ISSUE THREAD

**Issue by ReportCardsMC** [Romitou/MongoSK#7]
**All Documents of Collection**
 - **Syntax**: [all] [mongo[db]] documents  (of|in) %mongocollection%
 - **Description**: Get all the documents within a collection
 - **Example**: 
```
loop all mongo documents in {_collection}:
  broadcast loop-value
```

**Change Mongo Document**
 - **Syntax**: (first/all) [mongo[db]] document[s] where %string% (is|equals to) %object% (of|in) %mongocollection%
 - **Description**: Get the first or all documents where a value equals an object.
 - **Example**:
```
loop all mongo documents where "money" is 0 in {_collection}:
  delete mongo document loop-value in {_collection}
```

**Delete Mongo Document**
 - **Syntax**: delete [mongo[db]] document[s] %mongodocuments%
 - **Description**: Delete the mongo document[s] specified
 - **Example**:
```
set {_docs::*} to all mongo documents where "money" is "0" in {_collection}
set {_doc} to first mongo document where "id" is "1"
delete mongo documents {_docs::*}
delete mongo document {_doc}
```

**Comment by Romitou** [comment]
Hey!

Thank you for your suggestions.
They will be added to 1.2.0 as soon as possible. I will also try to add the different comparators of Mongo in this update.
